import React,{useCallback,useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {bankCall,bankMoney as money,makePaySchedule} from '../../lib/banking';
import '../../styles/banking.css';
import {getTeamFullName} from '../../data/teams';
const displayText=value=>String(value||'').replace(/\bB2J(?: Motorsports)?\b/gi,getTeamFullName('B2J'));
const accountName=account=>account?.kind==='team'?getTeamFullName(account.subject):displayText(account?.name);
const date=value=>value?new Date(value).toLocaleString():'';
export default function BankingPanel({team='',driverId='',admin=false,initialTab='ledger'}) {
 const [accounts,setAccounts]=useState([]),[selected,setSelected]=useState(''),[data,setData]=useState(null),[tab,setTab]=useState(initialTab),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[settings,setSettings]=useState(null),[roster,setRoster]=useState([]),[season,setSeason]=useState(''),[pending,setPending]=useState([]),[filter,setFilter]=useState(''),[loaded,setLoaded]=useState(false);
 useEffect(()=>setTab(initialTab),[initialTab]);
 const [offer,setOffer]=useState({driver:'',role:'driver',total:250000,method:'three',dates:['','',''],weeks:20,share:0});
 const [request,setRequest]=useState({kind:'loan',amount:'',reason:'',contract:'',chapter:'13',destination:''});
 const [correction,setCorrection]=useState({source:'',destination:'',amount:'',reason:''}),[transfer,setTransfer]=useState({team:'',amount:'',reason:''}),[numbers,setNumbers]=useState([]);
 const [seed,setSeed]=useState({amount:'',assets:''}),[caseForm,setCaseForm]=useState({driver:'',race:'',kind:'conduct',amount:'',reason:''});
 const load=useCallback(async()=>{
  let accountQuery=supabase.from('brl_bank_accounts').select('id,kind,subject,name');
  if(!admin)accountQuery=team?accountQuery.eq('kind','team').eq('subject',team):accountQuery.eq('kind','driver').eq('subject',String(driverId));
  const {data:rows,error:err}=await accountQuery.order('name');if(err)throw new Error('Install the league banking SQL first. '+err.message);
  const visible=(rows||[]).filter(a=>a.kind!=='external').filter(a=>admin||team?(admin||a.kind==='team'&&a.subject===team):(a.kind==='driver'&&a.subject===String(driverId)));
  setLoaded(true);setAccounts(visible);const id=visible.some(a=>a.id===selected)?selected:visible[0]?.id||'';setSelected(id);setData(id?await bankCall('read',{account:id}):null);
  const {data:cfg}=await supabase.from('brl_bank_settings').select('*').eq('id',true).single();setSettings(cfg);
  const {data:pool}=await supabase.from('number_pool').select('*').order('number');setNumbers(pool||[]);
  const {data:state}=await supabase.from('league_state').select('data').eq('season_name','irl-league').single();setSeason(state?.data?.activeSeasonId||'');const current=state?.data?.seasons?.find(s=>s.id===state?.data?.activeSeasonId);setRoster(current?.drivers||[]);
  if(admin){const {data:cases,error:e}=await supabase.from('brl_bank_cases').select('*').eq('status','pending').order('created_at');if(e)throw e;setPending(cases||[]);}
 },[selected,team,driverId,admin]);
 useEffect(()=>{let live=true;const refresh=()=>load().catch(e=>{if(live)setError(e.message);});refresh();const timer=setInterval(refresh,15000);return()=>{live=false;clearInterval(timer);};},[load]);
 async function run(fn,message='Saved.') {if(busy)return;setBusy(true);setError('');setStatus('');try{await fn();await load();setStatus(message);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const a=data?.account,owner=a?.kind==='team',driver=a?.kind==='driver';
 const tabs=['ledger','payments','contracts','notices',...(owner?['manufacturer','requests','numbers','transfers']:driver?['requests']:[]),...(admin?['admin']:[])];
 const contracts=data?.contracts||[];
 async function createOffer(e){e.preventDefault();await run(()=>bankCall('offer',{season_value:season,team_value:a.subject,driver_value:offer.driver,role_value:offer.role,total_value:Number(offer.total),method:offer.method,payment_schedule:makePaySchedule(offer.total,offer.method,offer.dates,offer.weeks),share:Number(offer.share)/100}),'Offer sent. Funds are reserved when the driver accepts.');}
 async function sendRequest(e){e.preventDefault();await run(()=>bankCall('request',{team_value:owner?a.subject:contracts.find(c=>c.id===request.contract)?.team,kind_value:driver?'buyout':request.kind,reason_value:request.reason,amount_value:Number(request.amount||0),details:{contract_id:request.contract,chapter:request.chapter,destination_team:request.destination}}),'Request sent for admin review.');}
 return <section className="brl-bank" aria-label="League banking">
  <header><div><small>BRL FINANCIAL CENTER</small><h2>{accountName(a)||'Team banking'}</h2><p>Payments, agreements and a complete transaction history.</p></div><select aria-label="Bank account" value={selected} onChange={e=>setSelected(e.target.value)}>{accounts.map(row=><option key={row.id} value={row.id}>{accountName(row)} · {row.kind}</option>)}</select></header>
  {error&&<p role="alert" className="bank-error">{error}</p>}{status&&<p role="status">{status}</p>}
  {settings?.enabled===false&&<p className="bank-banner">Banking is paused. Balances and transaction history remain available. Automatic payments are paused.</p>}
  {!a&&!error&&<p>{loaded?'Your team account has not been prepared yet. Contact league administration to set it up.':'Loading account…'}</p>}
  {a&&<div className="bank-balances"><div><small>CURRENT BALANCE</small><strong>{money(a.balance)}</strong></div><div><small>AVAILABLE AFTER COMMITMENTS</small><strong>{money(data.available)}</strong></div>{data.credit&&<div><small>CREDIT RATING</small><strong>{data.credit.grade} · {data.credit.score}/100</strong><span>{data.credit.overdue} overdue payments</span></div>}</div>}
  <nav aria-label="Financial sections">{tabs.map(name=><button key={name} aria-pressed={tab===name} onClick={()=>setTab(name)}>{name==='admin'?'Admin controls':name[0].toUpperCase()+name.slice(1)}</button>)}</nav>
  {tab==='ledger'&&<><input aria-label="Search transactions" placeholder="Search descriptions, categories or races" value={filter} onChange={e=>setFilter(e.target.value)}/><div className="bank-scroll"><table><thead><tr><th>Date</th><th>Description</th><th>Amount</th><th>Balance</th></tr></thead><tbody>{(data?.transactions||[]).filter(t=>`${t.category} ${t.description} ${t.race_name||''}`.toLowerCase().includes(filter.toLowerCase())).map(t=><tr key={t.id}><td>{date(t.created_at)}</td><td><b>{t.category}</b><span>{displayText(t.description)}{t.race_name?` · ${t.race_name}`:''}</span></td><td className={Number(t.amount)<0?'debit':'credit'}>{money(t.amount)}</td><td>{money(t.balance_after)}</td></tr>)}</tbody></table></div>{!data?.transactions?.length&&<p>No transactions yet.</p>}</>}
  {tab==='payments'&&<><p>Agreed payments run automatically on their due dates. Insufficient funds leave the payment overdue. Late payment permanently forfeits affected team race points.</p><div className="bank-scroll"><table><thead><tr><th>Due date</th><th>Payment</th><th>Amount</th><th>Status</th></tr></thead><tbody>{(data?.payments||[]).map(p=><tr key={p.id}><td>{date(p.due_at)}</td><td>{p.description}</td><td>{money(p.amount)}</td><td>{p.status}{p.status==='scheduled'&&new Date(p.due_at)<new Date()?' · OVERDUE':''}</td></tr>)}</tbody></table></div></>}
  {tab==='contracts'&&<>
   {owner&&<form onSubmit={createOffer}><h3>Offer compensation</h3><div className="bank-fields"><label>Driver<select required value={offer.driver} onChange={e=>setOffer({...offer,driver:e.target.value})}><option value="">Select a driver</option>{roster.map(d=><option key={d.id} value={d.id}>#{d.number} {d.name}</option>)}</select></label><label>Role<select value={offer.role} onChange={e=>setOffer({...offer,role:e.target.value,total:e.target.value==='franchise'?750000:e.target.value==='owner'?500000:250000})}><option value="driver">Driver</option><option value="franchise">Franchise driver</option><option value="owner">Owner management</option></select></label><label>Total agreed compensation<input required type="number" min="1" step=".01" value={offer.total} onChange={e=>setOffer({...offer,total:e.target.value})}/></label><label>Payment method<select value={offer.method} onChange={e=>setOffer({...offer,method:e.target.value})}><option value="lump">Lump sum</option><option value="three">Three installments</option><option value="weekly">Weekly</option></select></label>{Array.from({length:offer.method==='three'?3:1},(_,i)=><label key={i}>Payment date {i+1}<input required type="datetime-local" value={offer.dates[i]} onChange={e=>setOffer({...offer,dates:offer.dates.map((v,n)=>n===i?e.target.value:v)})}/></label>)}{offer.method==='weekly'&&<label>Number of weekly payments<input type="number" min="1" max="52" value={offer.weeks} onChange={e=>setOffer({...offer,weeks:e.target.value})}/></label>}<label>Contracted driver share of DNF fee (%)<input type="number" min="0" max="50" value={offer.share} onChange={e=>setOffer({...offer,share:e.target.value})}/></label></div><p>No-trade protection included. Early team release pays earned compensation plus 50% of remaining unearned compensation. Driver early exit requires a 150% buyout of remaining unearned compensation.</p><button disabled={busy}>Send offer</button></form>}
   {contracts.map(c=><article key={c.id}><h3>{c.driver_name} · {c.role}</h3><p>{money(c.total)} · {c.schedule_type} · {c.status} · {c.team}</p><p>No-trade protection · DNF fee share {Number(c.dnf_share)*100}%</p>{(c.schedule||[]).map((p,i)=><div key={i}>{date(p.due_at)} · {money(p.amount)}</div>)}{driver&&c.status==='offered'&&<div className="bank-actions"><button disabled={busy} onClick={()=>run(()=>bankCall('accept',{contract:c.id,accept:true}),'Contract accepted.')}>Agree and accept</button><button disabled={busy} onClick={()=>run(()=>bankCall('accept',{contract:c.id,accept:false}))}>Decline</button></div>}{driver&&c.status==='active'&&<button onClick={()=>{setRequest({...request,kind:'buyout',contract:c.id});setTab('requests');}}>Request early-exit buyout</button>}</article>)}
  </>}
  {tab==='manufacturer'&&<>
   {(data?.agreements||[]).map(g=><article key={g.id}><h3>{g.manufacturer} partnership · {g.status}</h3><p>Season base {money(g.base_funding)} · Funding reduction {g.cut_percent}% · {g.funded_at?'Funding received':'Funding pending'} · 5% funding tax</p><ul>{g.expectations.map((goal,i)=><li key={i}>{goal.label}</li>)}</ul></article>)}
   {(data?.tasks||[]).map(t=><article key={t.id}><h3>{t.title}</h3><p>{t.description}</p><p>{t.race_name} · Reward {money(t.reward)} before 5% tax · Accept before {date(t.deadline)} · {t.status}</p>{t.status==='offered'&&<div className="bank-actions"><button disabled={busy} onClick={()=>run(()=>bankCall('accept_task',{task:t.id,accept:true}))}>Accept task</button><button disabled={busy} onClick={()=>run(()=>bankCall('accept_task',{task:t.id,accept:false}))}>Decline</button></div>}</article>)}{!data?.tasks?.length&&<p>Manufacturer challenges appear during race week. Declining or failing an optional challenge creates no fine.</p>}
  </>}
  {(tab==='requests'||driver&&tab==='notices')&&<><form onSubmit={sendRequest}><h3>{driver?'Request a contract buyout':'Financial request'}</h3><div className="bank-fields">{owner&&<label>Request<select value={request.kind} onChange={e=>setRequest({...request,kind:e.target.value})}>{['loan','bankruptcy','release','reduction','trade'].map(k=><option key={k}>{k}</option>)}</select></label>}<label>Amount, if applicable<input type="number" min="0" step=".01" value={request.amount} onChange={e=>setRequest({...request,amount:e.target.value})}/></label><label>Contract<select value={request.contract} onChange={e=>setRequest({...request,contract:e.target.value})}><option value="">Select if applicable</option>{contracts.filter(c=>c.status==='active').map(c=><option key={c.id} value={c.id}>{c.driver_name} · {c.role}</option>)}</select></label>{request.kind==='bankruptcy'&&<label>Chapter<select value={request.chapter} onChange={e=>setRequest({...request,chapter:e.target.value})}><option value="7">7 · Closure</option><option value="13">13 · Restructuring</option></select></label>}{request.kind==='trade'&&<label>Destination team<input required value={request.destination} onChange={e=>setRequest({...request,destination:e.target.value})}/></label>}<label>Reason<input required minLength="3" value={request.reason} onChange={e=>setRequest({...request,reason:e.target.value})}/></label></div><button disabled={busy}>Submit for review</button></form></>}
  {(tab==='requests'||tab==='notices')&&(data?.cases||[]).map(c=><article key={c.id}><h3>{c.kind} · {c.status}</h3><p>{displayText(c.reason)}</p>{admin&&c.status==='approved'&&c.kind==='bankruptcy'&&<button disabled={busy} onClick={()=>{const note=window.prompt("Describe the verified settlement or completed repayment plan:");if(note)run(()=>bankCall('resolve',{case_id:c.id,note}));}}>Record bankruptcy resolution</button>}{driver&&['reduction','trade'].includes(c.kind)&&c.status==='pending'&&!c.driver_agreed_at&&<div className="bank-actions"><button disabled={busy} onClick={()=>run(()=>bankCall('consent',{case_id:c.id,agree:true}))}>Agree</button><button disabled={busy} onClick={()=>run(()=>bankCall('consent',{case_id:c.id,agree:false}))}>Decline</button></div>}</article>)}
  {tab==='notices'&&data?.reportCard&&<article><h3>Driver report card</h3><p>Missed media: {data.reportCard.missedMedia} · No-call/no-shows: {data.reportCard.noCallNoShow} · Confirmed DNF incidents: {data.reportCard.confirmedDnfs} · Conduct violations: {data.reportCard.conduct}</p><p>These records remain after a return to racing or late completion.</p></article>}
  {tab==='notices'&&(data?.notices||[]).map(n=><article key={n.id}><h3>{displayText(n.title)}</h3><small>{date(n.created_at)}</small><p>{displayText(n.detail)}</p></article>)}
  {tab==='numbers'&&owner&&<><h3>League number pool</h3><p>Numbers cost $10,000. Purchased numbers count as owned assets. Releasing an unassigned number refunds 50%. Assignment changes go through admin driver management.</p><div className="bank-scroll"><table><thead><tr><th>Number</th><th>Status</th><th>Action</th></tr></thead><tbody>{numbers.filter(n=>n.status==='available'||n.owning_team===a.subject).map(n=><tr key={n.id||n.number}><td>#{n.number}</td><td>{n.status}</td><td><button disabled={busy} onClick={()=>run(()=>bankCall('number',{team_value:a.subject,number_value:Number(n.number),buy:n.status==='available'}))}>{n.status==='available'?'Buy · $10,000':'Release to pool'}</button></td></tr>)}</tbody></table></div></>}
  {tab==='transfers'&&owner&&<form onSubmit={e=>{e.preventDefault();run(()=>bankCall('transfer',{team_value:a.subject,destination_team:transfer.team,value:Number(transfer.amount),reason_value:transfer.reason,reference:crypto.randomUUID()}),'Transfer posted.');}}><h3>Transfer funds to another team</h3><p>Only available funds can be transferred. Driver trades and contract changes require the protected request workflow.</p><div className="bank-fields"><label>Recipient team<input required value={transfer.team} onChange={e=>setTransfer({...transfer,team:e.target.value})}/></label><label>Amount<input required type="number" min=".01" step=".01" value={transfer.amount} onChange={e=>setTransfer({...transfer,amount:e.target.value})}/></label><label>Reason<input required minLength="3" value={transfer.reason} onChange={e=>setTransfer({...transfer,reason:e.target.value})}/></label></div><button disabled={busy}>Send transfer</button></form>}
  {tab==='admin'&&admin&&<>
   <div className="bank-actions"><button disabled={busy} onClick={()=>run(()=>bankCall('bootstrap'),'Accounts and manufacturer expectations prepared.')}>Prepare current-season accounts</button><button disabled={busy} onClick={()=>run(()=>bankCall('configure',{enable:!settings?.enabled,career_rate:Number(settings?.career_expense_rate??0)}),settings?.enabled?'Automatic banking paused.':'Automatic banking enabled.')}>{settings?.enabled?'Pause automatic banking':'Enable automatic banking'}</button><button disabled={busy} onClick={()=>run(()=>bankCall('tick'),'Due payments and approved race finances processed.')}>Process due transactions now</button></div>
   <p>5% driver income tax · 5% manufacturer funding tax · 5% annual net asset tax. Career expenses: {Number(settings?.career_expense_rate??0)*100}% of compensation. Starting balances are one-time entries; cash rolls forward.</p>
   <form onSubmit={e=>{e.preventDefault();run(()=>bankCall('configure',{enable:Boolean(settings?.enabled),career_rate:Number(seed.career??Number(settings?.career_expense_rate??0)*100)/100}),'Career expense rate saved.');}}><label>Driver career expense percentage (separate from 5% income tax)<input type="number" min="0" max="95" value={seed.career??Number(settings?.career_expense_rate??0)*100} onChange={e=>setSeed({...seed,career:e.target.value})}/></label><button disabled={busy}>Save expense rate</button></form>
   <form onSubmit={e=>{e.preventDefault();run(()=>bankCall('milestone',{season_value:season,driver_value:caseForm.driver,qualified:caseForm.qualified!==false}),'Chase qualification recorded.');}}><h3>Confirm Chase qualification</h3><select required value={caseForm.driver} onChange={e=>setCaseForm({...caseForm,driver:e.target.value})}><option value="">Select driver</option>{roster.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><label><input type="checkbox" checked={caseForm.qualified!==false} onChange={e=>setCaseForm({...caseForm,qualified:e.target.checked})}/>Qualified for the Chase</label><button disabled={busy}>Save qualification</button></form>
   {a&&<form onSubmit={e=>{e.preventDefault();run(()=>bankCall('seed',{team_or_kind:a.kind,subject_value:a.subject,value:Number(seed.amount),label:a.name}),'Opening balance posted once.');}}><h3>One-time opening balance: {accountName(a)}</h3><label>Approved balance<input required type="number" min=".01" step=".01" value={seed.amount} onChange={e=>setSeed({...seed,amount:e.target.value})}/></label><button disabled={busy}>Post opening balance</button></form>}
   {a&&['treasury','manufacturer'].includes(a.kind)&&<form onSubmit={e=>{e.preventDefault();run(()=>bankCall('budget',{kind_value:a.kind,subject_value:a.subject,season_value:season,value:Number(seed.budget)}),'Fixed season budget approved once.');}}><h3>Fixed current-season operating budget</h3><label>Allocation (one per account per season)<input required type="number" min="1" max="25000000" value={seed.budget||''} onChange={e=>setSeed({...seed,budget:e.target.value})}/></label><button disabled={busy}>Approve season budget</button></form>}
   {owner&&<form onSubmit={e=>{e.preventDefault();run(()=>bankCall('assets',{account:a.id,value:Number(seed.assets)}),'Owned asset valuation updated.');}}><h3>Owned assets excluding account cash</h3><input required type="number" min="0" step=".01" value={seed.assets} onChange={e=>setSeed({...seed,assets:e.target.value})}/><button disabled={busy}>Set asset value</button></form>}
   {owner&&<form onSubmit={e=>{e.preventDefault();run(()=>bankCall('admin_case',{team_value:a.subject,driver_value:caseForm.driver||null,race_value:caseForm.race||null,kind_value:caseForm.kind,reason_value:caseForm.reason,amount_value:Number(caseForm.amount||0),details:{}}));}}><h3>Record an incident for review</h3><div className="bank-fields"><label>Driver<select value={caseForm.driver} onChange={e=>setCaseForm({...caseForm,driver:e.target.value})}><option value="">Team</option>{roster.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Incident<select value={caseForm.kind} onChange={e=>setCaseForm({...caseForm,kind:e.target.value})}>{['conduct','attendance','dnf','termination'].map(k=><option key={k}>{k}</option>)}</select></label><label>Race<input value={caseForm.race} onChange={e=>setCaseForm({...caseForm,race:e.target.value})}/></label><label>Fine amount<input type="number" value={caseForm.amount} onChange={e=>setCaseForm({...caseForm,amount:e.target.value})}/></label><label>Reason<input required minLength="3" value={caseForm.reason} onChange={e=>setCaseForm({...caseForm,reason:e.target.value})}/></label></div><button disabled={busy}>Create review</button></form>}
   <form onSubmit={e=>{e.preventDefault();run(()=>bankCall('adjust',{source:correction.source,destination:correction.destination,value:Number(correction.amount),reason_value:correction.reason,reference:crypto.randomUUID()}),'Correction recorded as a separate ledger transaction.');}}><h3>Audited financial correction</h3><div className="bank-fields">{['source','destination'].map(field=><label key={field}>{field}<select required value={correction[field]} onChange={e=>setCorrection({...correction,[field]:e.target.value})}><option value="">Select account</option>{accounts.map(row=><option key={row.id} value={row.id}>{accountName(row)} · {row.kind}</option>)}</select></label>)}<label>Amount<input required type="number" min=".01" value={correction.amount} onChange={e=>setCorrection({...correction,amount:e.target.value})}/></label><label>Specific reason<input required minLength="8" value={correction.reason} onChange={e=>setCorrection({...correction,reason:e.target.value})}/></label></div><button disabled={busy}>Record correction</button></form>
   <h3>Pending decisions</h3>{pending.map(c=><article key={c.id}><h3>{getTeamFullName(c.team)} · {c.kind} {c.race_name?`· ${c.race_name}`:''}</h3><p>{displayText(c.reason)} · {money(c.amount)}</p><p>{JSON.stringify(c.payload)}{c.driver_agreed_at?' · Driver consent recorded':''}</p><div className="bank-actions"><button disabled={busy} onClick={()=>run(()=>bankCall('decide',{case_id:c.id,approve:true}))}>Approve / confirm</button><button disabled={busy} onClick={()=>run(()=>bankCall('decide',{case_id:c.id,approve:false}))}>Deny</button>{['attendance','dnf'].includes(c.kind)&&<button disabled={busy} onClick={()=>run(async()=>{await bankCall('case_note',{case_id:c.id,note:c.reason+' — Admin-approved absence or internet/power exemption',excused:true});await bankCall('decide',{case_id:c.id,approve:true});})}>Approve exemption</button>}</div></article>)}
  </>}
 </section>;
}
