import React,{useState} from 'react';
import {getTrackOverview,trackOverviewData} from '../../data/trackOverview';
import {physicalTrackName,validateSchedule,uploadTrackPhoto} from '../../utils/scheduleEditing';
import {useLeagueAccess,hasLeagueRole} from '../../lib/roleAccess';
import '../../styles/trackGuide.css';
const id=()=>crypto.randomUUID();
export default function ScheduleEditor({tracks=[],activeSeason,onSaveSchedule,supabase}){
 const {access,loading}=useLeagueAccess();
 const [rows,setRows]=useState(()=>tracks.map(t=>({...t,_key:id()})));
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const patch=(key,field,value)=>{setNotice('Unsaved changes.');setRows(rs=>rs.map(r=>r._key===key?{...r,[field]:value,...(field==="name"&&physicalTrackName(value)!==physicalTrackName(r.name)?{overview:rs.find(other=>other._key!==key&&physicalTrackName(other.name)===physicalTrackName(value))?.overview||{}}:{})}:r));};
 const patchProfile=(row,field,value)=>{const name=physicalTrackName(row.name);setNotice('Unsaved changes.');setRows(rs=>rs.map(r=>physicalTrackName(r.name)===name?{...r,overview:{...(r.overview||{}),[field]:value}}:r));};
 async function photo(row,file){setBusy(true);setError('');try{const url=await uploadTrackPhoto(supabase,file,row.name);patchProfile(row,'imageUrl',url);setNotice('Photo uploaded. Save schedule to publish it.');}catch(e){setError(e.message||'Photo upload failed.');}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');setNotice('Saving schedule…');try{const clean=validateSchedule(rows,activeSeason?.raceHistory||[]);await onSaveSchedule(clean);setRows(clean.map(t=>({...t,_key:id()})));setNotice('Schedule and track photos saved to Supabase.');}catch(e){setError(e.message||'Schedule save failed.');setNotice('Changes remain here; they have not been published.');}finally{setBusy(false);}}
 if(loading)return <p>Loading admin access…</p>;
 if(!hasLeagueRole(access,'full_admin'))return <p>Full admin access is required to edit the schedule and track photos.</p>;
 const names=[...new Set(Object.keys(trackOverviewData).filter(n=>!n.startsWith('Preseason - ')).map(physicalTrackName))].sort();
 return <section className="brl-track-guide brl-schedule-editor"><span className="brl-flow-kicker">Race Operations</span><h2>Schedule &amp; tracks</h2><p>Edit the calendar and track profiles here. All dates must be Saturdays. Photos and track details are shared across events at the same track.</p><datalist id="brl-track-names">{names.map(n=><option key={n} value={n}/>)}</datalist>
 <fieldset disabled={busy} style={{border:0,padding:0,margin:0}}>
 {rows.map((row,index)=>{const overview=getTrackOverview(row);const profileField=(label,name,type='text')=><label className="brl-guide-field" key={name}><span>{label}</span><input type={type} min={type==='number'?0:undefined} step={name==='lengthMiles'?'.001':'1'} value={overview[name]??''} onChange={e=>patchProfile(row,name,e.target.value)}/></label>;
 return <section className="brl-flow-section" key={row._key}><h3>Race {index+1}</h3><div className="brl-guide-fields"><label className="brl-guide-field"><span>Full track name</span><input list="brl-track-names" value={physicalTrackName(row.name)} onChange={e=>patch(row._key,'name',e.target.value)}/></label><label className="brl-guide-field"><span>Saturday date</span><input type="date" value={row.date||''} onChange={e=>patch(row._key,'date',e.target.value)}/></label><label className="brl-guide-field"><span>Season phase</span><select value={row.phase||'Regular Season'} onChange={e=>patch(row._key,'phase',e.target.value)}>{['Preseason','Regular Season','Chase'].map(p=><option key={p}>{p}</option>)}</select></label><label className="brl-guide-field"><span>Scoring stages</span><select value={row.stageCount||2} onChange={e=>patch(row._key,'stageCount',Number(e.target.value))}>{[1,2,3].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label className="brl-guide-field"><span>Event label</span><input placeholder="Crown jewel / Championship Race" value={row.eventLabel||''} onChange={e=>patch(row._key,'eventLabel',e.target.value)}/></label></div>
 {overview.imageUrl&&<img src={overview.imageUrl} alt={`${physicalTrackName(row.name)} track`} className="brl-admin-track-photo"/>}<label className="brl-guide-field"><span>Upload track photo (up to 10 MB)</span><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)photo(row,f);}}/></label>{overview.imageUrl&&<button type="button" onClick={()=>patchProfile(row,'imageUrl','')}>Remove photo</button>}
 <details><summary>Track facts and 50% / 3× strategy</summary><div className="brl-guide-fields">{profileField('Track length (miles)','lengthMiles','number')}{profileField('Surface','surface')}{profileField('Banking','banking')}{profileField('Pit speed (include mph / zones)','pitSpeed')}{profileField('Full-distance reference laps','referenceFullLaps','number')}{profileField('Confirmed 50% game laps','actualRaceLaps','number')}</div>{['preferredLine','savingGuidance','watchFor','referenceNote','restartZone'].map(name=><label key={name} className="brl-guide-field brl-guide-notes"><span>{{preferredLine:'Racing lines',savingGuidance:'3× fuel and tire guidance',watchFor:'Pit strategy and cautions',referenceNote:'Reference note',restartZone:'Restart-zone information'}[name]}</span><textarea rows={3} value={overview[name]||''} onChange={e=>patchProfile(row,name,e.target.value)}/></label>)}</details>
 <button type="button" onClick={()=>{setRows(rs=>rs.filter(r=>r._key!==row._key));setNotice('Unsaved changes.');}}>Remove race</button></section>;})}
 <button type="button" onClick={()=>{setRows(rs=>[...rs,{_key:id(),name:'',date:'',stageCount:2,phase:'Regular Season',eventLabel:''}]);setNotice('Unsaved changes.');}}>Add race</button></fieldset>
 <div className="brl-schedule-save"><button type="button" disabled={busy || typeof onSaveSchedule!=="function"} onClick={save}>{busy?'Working…':'Save schedule & track changes'}</button><p role="status">{notice}</p>{typeof onSaveSchedule!=="function"&&<p role="alert">Update App.jsx from this ZIP to enable schedule saving.</p>}{error&&<p role="alert" style={{color:'#b42318'}}>{error}</p>}</div></section>;
}
