import {useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
import {interviewPairs,mediaPersonas} from "../lib/aiMedia";
import "../styles/aiMedia.css";
export default function PublicInterviewsPage(){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;(async()=>{const state=await supabase.rpc("brl_read_league");if(state.error)throw state.error;const r=await supabase.from("brl_ai_sessions").select("id,driver_name,race_name,kind,persona,messages,updated_at").eq("season_id",state.data.activeSeasonId).eq("status","completed").in("kind",["pre","post"]).order("updated_at",{ascending:false}).limit(60);if(r.error)throw r.error;if(active)setItems(r.data||[]);})().catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[]);
 return <main className="brl-ai-media"><p className="brl-ai-kicker">Inside the paddock</p><h1>Drivers in their own words.</h1><p>Real reactions. One question at a time.</p><a href="/media">Complete my media interview</a>{loading&&<p>Loading interviews…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!items.length&&<p>The first interviews of this season will appear here.</p>}{items.map(s=><article key={s.id}><p>{s.kind==="pre"?"Pre-race":"Post-race"} · {s.race_name} · {mediaPersonas.find(p=>p[0]===s.persona)?.[1]||"BRL Reporter"}</p><h2>{s.driver_name}</h2><details><summary>Read interview</summary>{interviewPairs(s.messages).map((p,i)=><div key={i}><p><strong>{p.question}</strong></p><p>{p.answer}</p></div>)}{s.messages?.at(-1)?.role === "assistant" && <p><strong>{mediaPersonas.find(p=>p[0]===s.persona)?.[1]||"BRL Reporter"} (AI): </strong>{s.messages.at(-1).text}</p>}</details></article>)}<p className="brl-ai-notice">Interviewers are AI personas inspired by NASCAR broadcasters, not the real people or endorsed by them. Responses come from the drivers.</p></main>;
}
