import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
import { useLeagueAccess, hasLeagueRole } from "../../lib/roleAccess";
import { callMedia } from "../../lib/aiMedia";
import "../../styles/aiMedia.css";
export default function AIMediaAdmin() {
 const {access}=useLeagueAccess(); const allowed=hasLeagueRole(access,"full_admin");
 const [settings,setSettings]=useState(null),[articles,setArticles]=useState([]),[jobs,setJobs]=useState([]),[held,setHeld]=useState([]),[health,setHealth]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[edit,setEdit]=useState(null),[league,setLeague]=useState(null),[completed,setCompleted]=useState([]),[event,setEvent]=useState("");
 async function load(){
  const results=await Promise.all([supabase.from("brl_ai_settings").select("*").single(),supabase.from("brl_ai_articles").select("id,title,content,status,byline,category,review_reasons,created_at").order("created_at",{ascending:false}).limit(30),supabase.from("brl_ai_jobs").select("id,race_name,kind,status,error,created_at").order("created_at",{ascending:false}).limit(30),supabase.from("brl_ai_sessions").select("id,driver_name,race_name,messages,review_reasons").eq("status","review").order("updated_at",{ascending:false})]);
  for(const r of results)if(r.error)throw r.error;
  setSettings(results[0].data);setArticles(results[1].data);setJobs(results[2].data);setHeld(results[3].data);setHealth(await callMedia({action:"status"}));
  const state=await supabase.rpc("brl_read_league");if(state.error)throw state.error;setLeague(state.data);setEvent(v=>v||state.data.tracks?.[0]?.name||"");
  const records=await supabase.from("brl_ai_sessions").select("driver_id,race_name,kind,status,updated_at").eq("season_id",state.data.activeSeasonId).in("kind",["pre","post"]);if(records.error)throw records.error;setCompleted(records.data||[]);
 }
 useEffect(()=>{if(allowed)load().catch(e=>setError(e.message));},[allowed]);
 async function run(fn){if(busy)return;setBusy(true);setError("");try{await fn();await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function update(table,id,values){const r=await supabase.from(table).update(values).eq("id",id);if(r.error)throw r.error;}
 if(!allowed)return <p>Full Admin access is required.</p>;
 return <section className="brl-ai-media"><p className="brl-ai-kicker">Newsroom control</p><h2>AI Media</h2><p>Race recaps, previews and conversational interviews. Media completion fulfills contract obligations; interviews carry no payment.</p>{error&&<p role="alert" className="brl-ai-error">{error}</p>}
 {settings&&<><p>AI key: {health?.configured?"configured":"missing"} · Worker: {health?.workerConfigured?"configured":"missing"}</p><label><input type="checkbox" checked={settings.enabled} disabled={busy||!health?.configured||!health?.workerConfigured} onChange={e=>run(()=>update("brl_ai_settings",true,{enabled:e.target.checked}))}/> Enable automatic media</label><label> Daily API request limit <input type="number" min="1" max="2000" value={settings.max_daily_requests} onChange={e=>setSettings({...settings,max_daily_requests:Number(e.target.value)})}/></label><button disabled={busy} onClick={()=>run(()=>update("brl_ai_settings",true,{max_daily_requests:settings.max_daily_requests}))}>Save limit</button><p>This limits API requests, including moderation. It is not a dollar spending limit. Previews queue within seven days of a scheduled race.</p></>}
 <div className="brl-ai-actions"><button disabled={busy||!settings?.enabled} onClick={()=>run(()=>callMedia({action:"run"}))}>Process next article</button><button disabled={busy||!settings?.enabled} onClick={()=>run(()=>callMedia({action:"preview"}))}>Queue upcoming preview</button><button disabled={busy} onClick={()=>run(async()=>{})}>Refresh</button></div>
 <h3>Media obligations</h3><label>Race<select value={event} onChange={e=>setEvent(e.target.value)}>{league?.tracks?.map(t=><option key={t.name}>{t.name}</option>)}</select></label><p>Completion records for required interviews. Missing means incomplete, not automatically overdue. No automatic fine is applied.</p>{league?.seasons?.find(s=>s.id===league.activeSeasonId)?.drivers?.filter(d=>!d.retired).map(d=><div key={d.id} className="brl-ai-history-row"><span>#{d.number} {d.name}</span><span>{["pre","post"].map(kind=>`${kind}: ${completed.find(s=>String(s.driver_id)===String(d.id)&&s.race_name===event&&s.kind===kind)?.status||"missing"}`).join(" · ")}</span></div>)}
 <h3>Articles</h3>{articles.map(a=><article key={a.id}><p>{a.byline} · {a.category} · {a.status}</p><h3>{a.title}</h3><details><summary>Read article</summary><p style={{whiteSpace:"pre-wrap"}}>{a.content}</p></details>{a.review_reasons?.length>0&&<p>{a.review_reasons.join("; ")}</p>}<button disabled={busy} onClick={()=>setEdit({...a})}>Edit</button><button disabled={busy} onClick={()=>run(()=>update("brl_ai_articles",a.id,{status:"published",updated_at:new Date().toISOString()}))}>Publish</button><button disabled={busy} onClick={()=>run(()=>update("brl_ai_articles",a.id,{status:"hidden"}))}>Hide</button></article>)}
 {edit&&<form onSubmit={e=>{e.preventDefault();run(async()=>{await update("brl_ai_articles",edit.id,{title:edit.title,content:edit.content,updated_at:new Date().toISOString()});setEdit(null);});}}><label>Headline<input required maxLength="180" value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><label>Article<textarea required rows="12" value={edit.content} onChange={e=>setEdit({...edit,content:e.target.value})}/></label><button disabled={busy}>Save edit</button><button type="button" onClick={()=>setEdit(null)}>Cancel</button></form>}
 <h3>Interviews needing review</h3>{!held.length&&<p>No interviews need review.</p>}{held.map(s=><article key={s.id}><h3>{s.driver_name} · {s.race_name}</h3><p>{s.review_reasons?.join("; ")}</p><details><summary>Read conversation</summary>{s.messages.map((m,i)=><p key={i}><strong>{m.role=== "user"?s.driver_name:"Reporter"}:</strong> {m.text}</p>)}</details>{[true,false].map(publish=><button key={String(publish)} disabled={busy} onClick={()=>run(async()=>{const r=await supabase.rpc("brl_ai_review_session",{target:s.id,publish});if(r.error)throw r.error;})}>{publish?"Approve interview":"Close without publishing"}</button>)}</article>)}
 <h3>Generation queue</h3>{jobs.map(j=><div key={j.id} className="brl-ai-history-row"><span>{j.race_name} · {j.kind} · {j.status}{j.error&&<small>{j.error}</small>}</span>{["failed","done"].includes(j.status)&&<button disabled={busy||!settings?.enabled} onClick={()=>run(()=>callMedia({action:"retry",jobId:j.id}))}>{j.status==="done"?"Regenerate":"Retry"}</button>}</div>)}
 <p className="brl-ai-notice">Reporters and analysts are AI personas inspired by NASCAR broadcasters, not the real people or endorsed by them. Driver answers are their own words.</p></section>;
}
